server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
        - id: login_route
          uri: http://localhost:8001/
          predicates:
            - Path=/login
        - id: user_route
          uri: http://localhost:8001/
          predicates:
            - Path=/user
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: a67ef9b49b7ed20ffcbe
            client-secret: 6add602c4c1f8da6fbd0194a89df6ad1cd52e7f4
